### PR TITLE
Fix displaying last month expense

### PR DESCRIPTION
**Pull request by PRIHLOP**
Fix displaying last month expense, when new year started.

### CODE REVIEW

**Comment by AronNovak** [comment]
I tested the fix, it did something, but since an upgrade to the last version of Economizzer, for me, the revenue at the "Evolution" widget is yearly, the expenses are monthly, so there's something more to do.

**Comment by gugoan** [comment]
Hi,
I'll do some tests

**Comment by PRIHLOP** [comment]
Hi. Ok, I will check and fix mistakes.

**Comment by PRIHLOP** [comment]
1) Counting without my fix.
image
2) Counting with my fix.
image
3) List of transactions
image

This error accured becouse function SELECT from database include variable $thisyear, but if it is a first month in the year it do not count expense of previous month.

**Comment by gugoan** [comment]
tks man

**Pull request merged**
